import { z } from "zod";
import { openai } from "@/lib/openai";
import { db } from "@/lib/prisma";

export class QuestionGenerationError extends Error {
  constructor(message: string, public readonly code: string) {
    super(message);
    this.name = "QuestionGenerationError";
  }
}

/**
 * Zod schema for a single interview question generated by AI
 */
export const generatedQuestionSchema = z.object({
  question: z
    .string()
    .trim()
    .min(5, "Question text must be at least 5 characters"),
  expectedTopics: z
    .array(z.string().trim().min(1))
    .min(1, "At least one expected topic is required"),
  estimatedMinutes: z
    .number()
    .int()
    .min(1, "Estimated minutes must be at least 1")
    .max(30, "Estimated minutes must not exceed 30"),
  difficulty: z
    .string()
    .trim()
    .min(1, "Difficulty is required"),
  category: z
    .string()
    .trim()
    .min(1, "Category is required"),
});

export type GeneratedQuestion = z.infer<typeof generatedQuestionSchema>;

/**
 * Zod schema validating the full AI output containing between 10 and 15 questions
 */
export const generatedQuestionsResultSchema = z.object({
  questions: z
    .array(generatedQuestionSchema)
    .min(10, "AI must generate at least 10 interview questions")
    .max(15, "AI must generate at most 15 interview questions"),
});

export type GeneratedQuestionsResult = z.infer<typeof generatedQuestionsResultSchema>;

export interface GenerateQuestionsInput {
  role: string;
  company?: string | null;
  interviewType: "TECHNICAL" | "HR" | "SYSTEM_DESIGN" | "BEHAVIORAL" | string;
  difficulty: "EASY" | "MEDIUM" | "HARD" | string;
  resumeText?: string | null;
}

/**
 * Builds system and user prompt for OpenAI tailored to interview parameters
 */
export function buildQuestionPrompt(input: GenerateQuestionsInput): {
  systemPrompt: string;
  userPrompt: string;
} {
  const { role, company, interviewType, difficulty, resumeText } = input;

  const systemPrompt = `You are a Principal Engineering Recruiter and Technical Interview Architect.
Your task is to generate a comprehensive, structured set of interview questions tailored to the candidate's target role, interview type, difficulty, company, and resume (if available).

Rules:
1. Generate between 10 and 15 questions total.
2. Every question must strictly adhere to the requested Interview Type (${interviewType}) and Difficulty Level (${difficulty}).
3. For TECHNICAL interviews: focus on languages, frameworks, algorithms, concurrency, system programming, and practical debugging.
4. For SYSTEM_DESIGN interviews: focus on scalability, distributed systems, caching, database partitioning, latency, and real-world architectures.
5. For BEHAVIORAL interviews: focus on STAR methodology, conflict resolution, ownership, cross-functional collaboration, and technical leadership.
6. For HR interviews: focus on career aspirations, team dynamics, work ethics, communication, cultural alignment, and motivators.
7. If a target Company is specified (${company || "None"}), reflect that company's engineering values, architecture styles, and scale.
8. If a Candidate Resume is provided, tailor questions directly to their claimed technologies, past roles, and stated projects.
9. You must respond ONLY with a valid JSON object matching this schema:
{
  "questions": [
    {
      "question": "string (the clear, comprehensive interview question)",
      "expectedTopics": ["string", "string"] (core keywords and concepts the candidate should address),
      "estimatedMinutes": number (integer between 1 and 15),
      "difficulty": "string (e.g. Easy, Medium, or Hard)",
      "category": "string (e.g. Architecture, Algorithms, Leadership, Culture, Frameworks)"
    }
  ]
}`;

  let userPrompt = `CANDIDATE INTERVIEW SPECIFICATIONS:
- Target Role: ${role}
- Interview Type: ${interviewType}
- Target Difficulty: ${difficulty}
- Target Company: ${company?.trim() ? company.trim() : "General Industry Standard"}`;

  if (resumeText && resumeText.trim().length > 0) {
    userPrompt += `\n\nCANDIDATE RESUME EXTRACT:\n${resumeText.trim()}`;
  } else {
    userPrompt += `\n\n(No resume provided: generate questions covering industry-standard expectations for this role and seniority).`;
  }

  return { systemPrompt, userPrompt };
}

/**
 * Sends interview context to OpenAI and validates the returned questions
 * Never fabricates AI questions when OpenAI fails.
 *
 * @throws QuestionGenerationError if OpenAI request or validation fails
 */
export async function generateInterviewQuestions(
  input: GenerateQuestionsInput
): Promise<GeneratedQuestion[]> {
  const { systemPrompt, userPrompt } = buildQuestionPrompt(input);

  let rawContent: string | null = null;
  try {
    const completion = await openai.chat.completions.create({
      model: process.env.OPENAI_MODEL || "gpt-4o-mini",
      messages: [
        { role: "system", content: systemPrompt },
        { role: "user", content: userPrompt },
      ],
      response_format: { type: "json_object" },
      temperature: 0.3,
    });

    rawContent = completion.choices[0]?.message?.content ?? null;
  } catch (apiErr: unknown) {
    const message = apiErr instanceof Error ? apiErr.message : String(apiErr);
    throw new QuestionGenerationError(`OpenAI question generation failed: ${message}`, "OPENAI_API_ERROR");
  }

  if (!rawContent) {
    throw new QuestionGenerationError("OpenAI returned an empty response.", "EMPTY_RESPONSE");
  }

  let parsed: unknown;
  try {
    parsed = JSON.parse(rawContent);
  } catch {
    throw new QuestionGenerationError("Failed to parse OpenAI response as JSON.", "INVALID_JSON");
  }

  const validation = generatedQuestionsResultSchema.safeParse(parsed);
  if (!validation.success) {
    const details = validation.error.issues.map((i) => `${i.path.join(".")}: ${i.message}`).join("; ");
    throw new QuestionGenerationError(`AI questions failed schema validation: ${details}`, "SCHEMA_VALIDATION_FAILED");
  }

  return validation.data.questions;
}

/**
 * Persists an array of generated questions into the InterviewQuestion Prisma table
 * linked to the given interviewSessionId in order.
 */
export async function saveInterviewQuestions(
  interviewSessionId: string,
  questions: GeneratedQuestion[]
) {
  const createdQuestions = await Promise.all(
    questions.map((q, index) =>
      db.interviewQuestion.create({
        data: {
          interviewSessionId,
          question: q.question,
          expectedTopics: {
            topics: q.expectedTopics,
            estimatedMinutes: q.estimatedMinutes,
            difficulty: q.difficulty,
            category: q.category,
          },
          order: index + 1,
        },
      })
    )
  );

  return createdQuestions;
}
